server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

claim:
  management:
    client:
      url: http://claim-management:8022/v1/cm
      networkTimeout: 30000

dominant:
  client:
    url: http://dominant:8022/v1/domain/repository_client
    networkTimeout: 5000

kafka:
  bootstrap:
    servers: "localhost:9092"
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    concurrency: 5
    client-id: autoapprove
    group-id: "AutoApproveListener"
    enable-auto-commit: false
    auto-offset-reset: latest
    max-poll-records: 20
    connections-max-idle-ms: 300000
    session-timeout-ms: 300000
  topic: "claim-event-sink"
  retry-policy:
    maxAttempts: 10
