server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: autoapprove
      group-id: "AutoApproveListener"
      enable-auto-commit: false
      auto-offset-reset: latest
      max-poll-records: 20
      properties:
        connections.max.idle.ms: 300000
        session.timeout.ms: 300000
info:
  version: '@project.version@'
  stage: dev

claim:
  management:
    client:
      url: http://claim-management:8022/v1/cm
      networkTimeout: 30000

dominant:
  client:
    url: http://dominant:8022/v1/domain/repository_client
    networkTimeout: 5000

kafka:
  topic: "claim-event-sink"
  consumer:
    concurrency: 5
  retry-policy:
    maxAttempts: 10
    authErrorRetrySec: 60
